groups:
    - bash
    - developer
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - sudoalt::default
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::set_computer_name
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_set_preferred_view_style
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_display_full_path
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::tap_to_click

attributes:
    sublime_text_packages:
        -
            name: SideBarEnhancements
            source: https://github.com/titoBouzout/SideBarEnhancements
            branch: st3
        -
            name: GitGutter
            source: https://github.com/jisaacks/GitGutter.git
            branch: master
        -
            name: SCSS
            source: https://github.com/MarioRicalde/SCSS.tmbundle.git
            branch: SublimeText2
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: ST3
        -
            name: PHP-Twig
            source: https://github.com/Anomareh/PHP-Twig.tmbundle.git
            branch: master
        -
            name: Theme - Aqua
            source: https://github.com/cafarm/aqua-theme.git
            branch: master
        -
            name: Base16
            source: https://github.com/chriskempson/base16-textmate.git
            branch: master
        -
            name: ApplySyntax
            source: https://github.com/facelessuser/ApplySyntax.git
            branch: ST3
        -
            name: Theme - Flatland
            source: git://github.com/thinkpixellab/flatland.git
            branch: master
    git:
        name: Mario Carvalho
        email: marioacarvalho@gmail.com
    osxdefaults:
        computername: MarioMacbookPro
    authorization:
        sudo:
            users:
                - mariocarvalho
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - pwgen
            - pv
            - htop-osx
            - git-flow
            - siege
            - watch
        cask_apps:
            - dropbox
            - istat-menus
            - kaleidoscope
            - spotify
            - caffeine
            - vlc
            - slack
            - flashlight
            - vagrant-manager
            - vagrant
            - superduper
            - sourcetree
            - sequel-pro
            - the-unarchiver
            - cocoarestclient
            - charles